// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package org.googlecode.protobuf.netty.example;

import com.google.protobuf.AbstractMessage;

public final class Calculator {
  private Calculator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CalcRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 op1 = 1;
    /**
     * <code>required int32 op1 = 1;</code>
     */
    boolean hasOp1();
    /**
     * <code>required int32 op1 = 1;</code>
     */
    int getOp1();

    // required int32 op2 = 2;
    /**
     * <code>required int32 op2 = 2;</code>
     */
    boolean hasOp2();
    /**
     * <code>required int32 op2 = 2;</code>
     */
    int getOp2();
  }
  /**
   * Protobuf type {@code CalcRequest}
   */
  public static final class CalcRequest extends
      com.google.protobuf.GeneratedMessage
      implements CalcRequestOrBuilder {
    // Use CalcRequest.newBuilder() to construct.
    private CalcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalcRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalcRequest defaultInstance;
    public static CalcRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CalcRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              op1_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              op2_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Calculator.internal_static_CalcRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Calculator.internal_static_CalcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Calculator.CalcRequest.class, Calculator.CalcRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CalcRequest> PARSER =
        new com.google.protobuf.AbstractParser<CalcRequest>() {
      public CalcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalcRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalcRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 op1 = 1;
    public static final int OP1_FIELD_NUMBER = 1;
    private int op1_;
    /**
     * <code>required int32 op1 = 1;</code>
     */
    public boolean hasOp1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 op1 = 1;</code>
     */
    public int getOp1() {
      return op1_;
    }

    // required int32 op2 = 2;
    public static final int OP2_FIELD_NUMBER = 2;
    private int op2_;
    /**
     * <code>required int32 op2 = 2;</code>
     */
    public boolean hasOp2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 op2 = 2;</code>
     */
    public int getOp2() {
      return op2_;
    }

    private void initFields() {
      op1_ = 0;
      op2_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOp1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOp2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, op1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, op2_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, op1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, op2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Calculator.CalcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Calculator.CalcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Calculator.CalcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Calculator.CalcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Calculator.CalcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Calculator.CalcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Calculator.CalcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Calculator.CalcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Calculator.CalcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Calculator.CalcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Calculator.CalcRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Calculator.CalcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Calculator.internal_static_CalcRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Calculator.internal_static_CalcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Calculator.CalcRequest.class, Calculator.CalcRequest.Builder.class);
      }

      // Construct using Calculator.CalcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        op1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        op2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Calculator.internal_static_CalcRequest_descriptor;
      }

      public Calculator.CalcRequest getDefaultInstanceForType() {
        return Calculator.CalcRequest.getDefaultInstance();
      }

      public Calculator.CalcRequest build() {
        Calculator.CalcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public Calculator.CalcRequest buildPartial() {
        Calculator.CalcRequest result = new Calculator.CalcRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.op1_ = op1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.op2_ = op2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Calculator.CalcRequest) {
          return mergeFrom((Calculator.CalcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Calculator.CalcRequest other) {
        if (other == Calculator.CalcRequest.getDefaultInstance()) return this;
        if (other.hasOp1()) {
          setOp1(other.getOp1());
        }
        if (other.hasOp2()) {
          setOp2(other.getOp2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOp1()) {
          
          return false;
        }
        if (!hasOp2()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Calculator.CalcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Calculator.CalcRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 op1 = 1;
      private int op1_ ;
      /**
       * <code>required int32 op1 = 1;</code>
       */
      public boolean hasOp1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 op1 = 1;</code>
       */
      public int getOp1() {
        return op1_;
      }
      /**
       * <code>required int32 op1 = 1;</code>
       */
      public Builder setOp1(int value) {
        bitField0_ |= 0x00000001;
        op1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 op1 = 1;</code>
       */
      public Builder clearOp1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        op1_ = 0;
        onChanged();
        return this;
      }

      // required int32 op2 = 2;
      private int op2_ ;
      /**
       * <code>required int32 op2 = 2;</code>
       */
      public boolean hasOp2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 op2 = 2;</code>
       */
      public int getOp2() {
        return op2_;
      }
      /**
       * <code>required int32 op2 = 2;</code>
       */
      public Builder setOp2(int value) {
        bitField0_ |= 0x00000002;
        op2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 op2 = 2;</code>
       */
      public Builder clearOp2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        op2_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CalcRequest)
    }

    static {
      defaultInstance = new CalcRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CalcRequest)
  }

  public interface CalcResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 result = 1;
    /**
     * <code>required int32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code CalcResponse}
   */
  public static final class CalcResponse extends
      com.google.protobuf.GeneratedMessage
      implements CalcResponseOrBuilder {
    // Use CalcResponse.newBuilder() to construct.
    private CalcResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalcResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalcResponse defaultInstance;
    public static CalcResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CalcResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Calculator.internal_static_CalcResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Calculator.internal_static_CalcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Calculator.CalcResponse.class, Calculator.CalcResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CalcResponse> PARSER =
        new com.google.protobuf.AbstractParser<CalcResponse>() {
      public CalcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalcResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalcResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Calculator.CalcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Calculator.CalcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Calculator.CalcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Calculator.CalcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Calculator.CalcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Calculator.CalcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Calculator.CalcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Calculator.CalcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Calculator.CalcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Calculator.CalcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Calculator.CalcResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Calculator.CalcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Calculator.internal_static_CalcResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Calculator.internal_static_CalcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Calculator.CalcResponse.class, Calculator.CalcResponse.Builder.class);
      }

      // Construct using Calculator.CalcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Calculator.internal_static_CalcResponse_descriptor;
      }

      public Calculator.CalcResponse getDefaultInstanceForType() {
        return Calculator.CalcResponse.getDefaultInstance();
      }

      public Calculator.CalcResponse build() {
        Calculator.CalcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public Calculator.CalcResponse buildPartial() {
        Calculator.CalcResponse result = new Calculator.CalcResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Calculator.CalcResponse) {
          return mergeFrom((Calculator.CalcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Calculator.CalcResponse other) {
        if (other == Calculator.CalcResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Calculator.CalcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Calculator.CalcResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 result = 1;
      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CalcResponse)
    }

    static {
      defaultInstance = new CalcResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CalcResponse)
  }

  /**
   * Protobuf service {@code CalcService}
   */
  public static abstract class CalcService
      implements com.google.protobuf.Service {
    protected CalcService() {}

    public interface Interface {
      /**
       * <code>rpc Add(.CalcRequest) returns (.CalcResponse);</code>
       */
      public abstract void add(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request,
          com.google.protobuf.RpcCallback<Calculator.CalcResponse> done);

      /**
       * <code>rpc Subtract(.CalcRequest) returns (.CalcResponse);</code>
       */
      public abstract void subtract(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request,
          com.google.protobuf.RpcCallback<Calculator.CalcResponse> done);

      /**
       * <code>rpc Multiply(.CalcRequest) returns (.CalcResponse);</code>
       */
      public abstract void multiply(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request,
          com.google.protobuf.RpcCallback<Calculator.CalcResponse> done);

      /**
       * <code>rpc Divide(.CalcRequest) returns (.CalcResponse);</code>
       */
      public abstract void divide(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request,
          com.google.protobuf.RpcCallback<Calculator.CalcResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CalcService() {
        @java.lang.Override
        public  void add(
            com.google.protobuf.RpcController controller,
            Calculator.CalcRequest request,
            com.google.protobuf.RpcCallback<Calculator.CalcResponse> done) {
          impl.add(controller, request, done);
        }

        @java.lang.Override
        public  void subtract(
            com.google.protobuf.RpcController controller,
            Calculator.CalcRequest request,
            com.google.protobuf.RpcCallback<Calculator.CalcResponse> done) {
          impl.subtract(controller, request, done);
        }

        @java.lang.Override
        public  void multiply(
            com.google.protobuf.RpcController controller,
            Calculator.CalcRequest request,
            com.google.protobuf.RpcCallback<Calculator.CalcResponse> done) {
          impl.multiply(controller, request, done);
        }

        @java.lang.Override
        public  void divide(
            com.google.protobuf.RpcController controller,
            Calculator.CalcRequest request,
            com.google.protobuf.RpcCallback<Calculator.CalcResponse> done) {
          impl.divide(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.add(controller, (Calculator.CalcRequest)request);
            case 1:
              return impl.subtract(controller, (Calculator.CalcRequest)request);
            case 2:
              return impl.multiply(controller, (Calculator.CalcRequest)request);
            case 3:
              return impl.divide(controller, (Calculator.CalcRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return Calculator.CalcRequest.getDefaultInstance();
            case 1:
              return Calculator.CalcRequest.getDefaultInstance();
            case 2:
              return Calculator.CalcRequest.getDefaultInstance();
            case 3:
              return Calculator.CalcRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return Calculator.CalcResponse.getDefaultInstance();
            case 1:
              return Calculator.CalcResponse.getDefaultInstance();
            case 2:
              return Calculator.CalcResponse.getDefaultInstance();
            case 3:
              return Calculator.CalcResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc Add(.CalcRequest) returns (.CalcResponse);</code>
     */
    public abstract void add(
        com.google.protobuf.RpcController controller,
        Calculator.CalcRequest request,
        com.google.protobuf.RpcCallback<Calculator.CalcResponse> done);

    /**
     * <code>rpc Subtract(.CalcRequest) returns (.CalcResponse);</code>
     */
    public abstract void subtract(
        com.google.protobuf.RpcController controller,
        Calculator.CalcRequest request,
        com.google.protobuf.RpcCallback<Calculator.CalcResponse> done);

    /**
     * <code>rpc Multiply(.CalcRequest) returns (.CalcResponse);</code>
     */
    public abstract void multiply(
        com.google.protobuf.RpcController controller,
        Calculator.CalcRequest request,
        com.google.protobuf.RpcCallback<Calculator.CalcResponse> done);

    /**
     * <code>rpc Divide(.CalcRequest) returns (.CalcResponse);</code>
     */
    public abstract void divide(
        com.google.protobuf.RpcController controller,
        Calculator.CalcRequest request,
        com.google.protobuf.RpcCallback<Calculator.CalcResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return Calculator.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.add(controller, (Calculator.CalcRequest)request,
            com.google.protobuf.RpcUtil.<Calculator.CalcResponse>specializeCallback(
              done));
          return;
        case 1:
          this.subtract(controller, (Calculator.CalcRequest)request,
            com.google.protobuf.RpcUtil.<Calculator.CalcResponse>specializeCallback(
              done));
          return;
        case 2:
          this.multiply(controller, (Calculator.CalcRequest)request,
            com.google.protobuf.RpcUtil.<Calculator.CalcResponse>specializeCallback(
              done));
          return;
        case 3:
          this.divide(controller, (Calculator.CalcRequest)request,
            com.google.protobuf.RpcUtil.<Calculator.CalcResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return Calculator.CalcRequest.getDefaultInstance();
        case 1:
          return Calculator.CalcRequest.getDefaultInstance();
        case 2:
          return Calculator.CalcRequest.getDefaultInstance();
        case 3:
          return Calculator.CalcRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return Calculator.CalcResponse.getDefaultInstance();
        case 1:
          return Calculator.CalcResponse.getDefaultInstance();
        case 2:
          return Calculator.CalcResponse.getDefaultInstance();
        case 3:
          return Calculator.CalcResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends Calculator.CalcService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void add(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request,
          com.google.protobuf.RpcCallback<Calculator.CalcResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          Calculator.CalcResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            Calculator.CalcResponse.class,
            Calculator.CalcResponse.getDefaultInstance()));
      }

      public  void subtract(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request,
          com.google.protobuf.RpcCallback<Calculator.CalcResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          Calculator.CalcResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            Calculator.CalcResponse.class,
            Calculator.CalcResponse.getDefaultInstance()));
      }

      public  void multiply(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request,
          com.google.protobuf.RpcCallback<Calculator.CalcResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          Calculator.CalcResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            Calculator.CalcResponse.class,
            Calculator.CalcResponse.getDefaultInstance()));
      }

      public  void divide(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request,
          com.google.protobuf.RpcCallback<Calculator.CalcResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          Calculator.CalcResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            Calculator.CalcResponse.class,
            Calculator.CalcResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public Calculator.CalcResponse add(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request)
          throws com.google.protobuf.ServiceException;

      public Calculator.CalcResponse subtract(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request)
          throws com.google.protobuf.ServiceException;

      public Calculator.CalcResponse multiply(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request)
          throws com.google.protobuf.ServiceException;

      public Calculator.CalcResponse divide(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public Calculator.CalcResponse add(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request)
          throws com.google.protobuf.ServiceException {
        return (Calculator.CalcResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          Calculator.CalcResponse.getDefaultInstance());
      }


      public Calculator.CalcResponse subtract(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request)
          throws com.google.protobuf.ServiceException {
        return (Calculator.CalcResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          Calculator.CalcResponse.getDefaultInstance());
      }


      public Calculator.CalcResponse multiply(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request)
          throws com.google.protobuf.ServiceException {
        return (Calculator.CalcResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          Calculator.CalcResponse.getDefaultInstance());
      }


      public Calculator.CalcResponse divide(
          com.google.protobuf.RpcController controller,
          Calculator.CalcRequest request)
          throws com.google.protobuf.ServiceException {
        return (Calculator.CalcResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          Calculator.CalcResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:CalcService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CalcRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CalcRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CalcResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CalcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\"\'\n\013CalcRequest\022\013\n\003op1\030\001 " +
      "\002(\005\022\013\n\003op2\030\002 \002(\005\"\036\n\014CalcResponse\022\016\n\006resu" +
      "lt\030\001 \002(\0052\252\001\n\013CalcService\022\"\n\003Add\022\014.CalcRe" +
      "quest\032\r.CalcResponse\022\'\n\010Subtract\022\014.CalcR" +
      "equest\032\r.CalcResponse\022\'\n\010Multiply\022\014.Calc" +
      "Request\032\r.CalcResponse\022%\n\006Divide\022\014.CalcR" +
      "equest\032\r.CalcResponseB6\n%com.googlecode." +
      "protobuf.netty.exampleB\nCalculator\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CalcRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CalcRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CalcRequest_descriptor,
              new java.lang.String[] { "Op1", "Op2", });
          internal_static_CalcResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CalcResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CalcResponse_descriptor,
              new java.lang.String[] { "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
